## Question - 1
Write Python code that does the following. 

- Create a function: **two_bit_comparator()**, Input: **input_value_a**, **input_value_b** where input_value_a and input_value_b should be unsigned two bit binary value. This function should COMPARE the two bits and return the appropraite value, Here the output should be a three bit binary value where LSB signifies that input_a is greater than input_b, MSB signifies that input_b is greater than input_a and the Middle bit signifies that input_a is equal to input_b.

    - Ex: input_value_a = 10, input_value_b = 00 then input_value_a COMPARED with input_value_b would result in output_value = 100 (Here MSB is 1 and rest are 0 signifying that input_value_a is greater than input_value_b
    - Ex: input_value_a = 01, input_value_b = 10 then input_value_a COMPARED with input_value_b would result in output_value = 001 (Here MSB is 1 and rest are 0 signifying that input_value_b is greater than input_value_a
    - Ex: input_value_a = 01, input_value_b = 01 then input_value_a COMPARED with input_value_b would result in output_value = 010 (Here Middle bit is 1 and rest are 0 signifying that input_value_a is greater than input_value_b

**Conditions to follow:**
- The output should be a string format similar to test cases mentioned below
- **IMPORTANT: You cannot use any Python [mathematical operators](https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp) in your solution.**
- Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- No other function name can be defined/declared than the ones asked to be declared in any of the questions presented in this notebook. 
- The code you write should pass all the test cases given. 


---

TEST CASES:

```
Input A: 11 COMPARED with Input B: 00 is 100

Input A: 10 COMPARED with Input B: 10 is 010

Input A: 00 COMPARED with Input B: 11 is 001

Input A: 10 COMPARED with Input B: 01 is 100
```
---

Hint: You can use built in methods and data type/string methods to create the solution to solve this problem. Consider using logic gates from above solutions and solving the k-map equation using those gates for a two bit comparator 


### Code

In [ ]:
# DECLARE the function two_bit_comparator()
def two_bit_comparator(input_value_a, input_value_b):
    # write code here

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('11', '00'), ('10', '10'), ('00', '11'), ('10', '01')]
for input_value_a, input_value_b in input_value_tuple_list:
    # CALL the two_bit_comparator with required parameters
    output_value = two_bit_comparator(input_value_a=input_value_a, input_value_b=input_value_b)
    # Print the output
    print("Input A: {0} COMPARED with Input B: {1} is {2}\n".format(input_value_a, input_value_b, output_value))

### Solution

In [2]:
# DECLARE the function and_gate()
def and_gate(input_value_a, input_value_b):
    # We will add zeros to the MSB if the length is less than 4
    input_value_a = input_value_a.zfill(4)
    input_value_b = input_value_b.zfill(4)
    # Initialize the output_value_list
    output_value_list = []
    # Iterate over both input, bit by bit
    for bit_a, bit_b in zip(input_value_a, input_value_b):
        # AND GATE output is 1 only when both inputs are 1 and 0 otherwise
        output_value_list.append('1' if (bit_a == '1') and (bit_b == '1') else '0')
    # Return the output value as string        
    return "".join(output_value_list)

# DECLARE the function or_gate()
def or_gate(input_value_a, input_value_b):
    # We will add zeros to the MSB if the length is less than 4
    input_value_a = input_value_a.zfill(4)
    input_value_b = input_value_b.zfill(4)
    # Initialize the output_value_list
    output_value_list = []
    # Iterate over both input, bit by bit
    for bit_a, bit_b in zip(input_value_a, input_value_b):
        # OR GATE output is 1 only when either inputs are 1 and 0 otherwise
        output_value_list.append('1' if (bit_a == '1') or (bit_b == '1') else '0')
    # Return the output value as string        
    return "".join(output_value_list)

# DECLARE the function xor_gate()
def xor_gate(input_value_a, input_value_b):
    # We will add zeros to the MSB if the length is less than 4
    input_value_a = input_value_a.zfill(4)
    input_value_b = input_value_b.zfill(4)
    # Initialize the output_value_list
    output_value_list = []
    # Iterate over both input, bit by bit
    for bit_a, bit_b in zip(input_value_a, input_value_b):
        # XOR GATE output is 1 only when both inputs are not equal to each other and 0 otherwise
        output_value_list.append('1' if (bit_a != bit_b) else '0')
    # Return the output value as string        
    return "".join(output_value_list)

# DECLARE the function not_gate()
def not_gate(input_value):
    # Switch the places of 1 and 0 in the input value string
    input_value = input_value.replace('1', 'X').replace('0', '1').replace('X', '0')
    # Return the output value as string        
    return input_value

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('01', '1111'), ('1010', '101')]
for input_value_a, input_value_b in input_value_tuple_list:
        # CALL the and_gate with required parameters
    and_gate_output_value = and_gate(input_value_a=input_value_a, input_value_b=input_value_b)
    # CALL the or_gate with required parameters
    or_gate_output_value = or_gate(input_value_a=input_value_a, input_value_b=input_value_b)
    # CALL the xor_gate with required parameters
    xor_gate_output_value = xor_gate(input_value_a=input_value_a, input_value_b=input_value_b)
    # CALL the not_gate with required parameters
    not_gate_a_output_value = not_gate(input_value=input_value_a)
    not_gate_b_output_value = not_gate(input_value=input_value_b)
    # Print the output
    print("Input A: {0} AND Input B: {1} is {2}\n".format(input_value_a, input_value_b, and_gate_output_value))
    print("Input A: {0} OR Input B: {1} is {2}\n".format(input_value_a, input_value_b, or_gate_output_value))
    print("Input A: {0} XOR Input B: {1} is {2}\n".format(input_value_a, input_value_b, xor_gate_output_value))
    print("Input A: {0} NOT is {2}, Input B: {1} NOT is {3}\n".format(input_value_a, input_value_b, not_gate_a_output_value, not_gate_b_output_value))

Input A: 01 AND Input B: 1111 is 0001

Input A: 01 OR Input B: 1111 is 1111

Input A: 01 XOR Input B: 1111 is 1110

Input A: 01 NOT is 10, Input B: 1111 NOT is 0000

Input A: 1010 AND Input B: 101 is 0000

Input A: 1010 OR Input B: 101 is 1111

Input A: 1010 XOR Input B: 101 is 1111

Input A: 1010 NOT is 0101, Input B: 101 NOT is 010



In [3]:
# DECLARE the function two_bit_comparator()
def two_bit_comparator(input_value_a, input_value_b):
    a_greater_than_b = '0'
    a_equal_to_b = '0'
    a_lesser_than_b = '0'
    a2, a1 = input_value_a
    b2, b1 = input_value_b
    # We will get all the formulas once we solve the k-map
    # A > B = ~B2.A2 + ~B1.A2.A1 + ~B2.~B1.A1
    # ~B2.A2
    part_1 = and_gate(not_gate(b2), a2)[-1]
    # ~B1.A2.A1
    part_2 = and_gate(and_gate(not_gate(b1), a2)[-1], a1)[-1]
    # ~B2.~B1.A1
    part_3 = and_gate(and_gate(not_gate(b2), not_gate(b1))[-1], a1)[-1]
    a_greater_than_b = or_gate(or_gate(part_1, part_2)[-1], part_3)[-1]
    # A = B = (A2 XNOR B2) . (A1 XNOR B1)
    # (A2 XNOR B2)
    part_1 = not_gate(xor_gate(a2, b2)[-1])
    # (A1 XNOR B1)
    part_2 = not_gate(xor_gate(a1, b1)[-1])
    a_equal_to_b = and_gate(part_1, part_2)[-1]
    # A > B = B2.~A2 + B1.~A2.~A1 + B2.B1.~A1
    # B2.~A2
    part_1 = and_gate(b2, not_gate(a2))[-1]
    # B1.~A2.~A1
    part_2 = and_gate(and_gate(b1, not_gate(a2))[-1], not_gate(a1))[-1]
    # B2.B1.~A1
    part_3 = and_gate(and_gate(b2, b1)[-1], not_gate(a1))[-1]
    a_lesser_than_b = or_gate(or_gate(part_1, part_2)[-1], part_3)[-1]
    return f"{a_greater_than_b}{a_equal_to_b}{a_lesser_than_b}"

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('11', '00'), ('10', '10'), ('00', '11'), ('10', '01')]
for input_value_a, input_value_b in input_value_tuple_list:
    # CALL the two_bit_comparator with required parameters
    output_value = two_bit_comparator(input_value_a=input_value_a, input_value_b=input_value_b)
    # Print the output
    print("Input A: {0} COMPARED with Input B: {1} is {2}\n".format(input_value_a, input_value_b, output_value))

Input A: 11 COMPARED with Input B: 00 is 100

Input A: 10 COMPARED with Input B: 10 is 010

Input A: 00 COMPARED with Input B: 11 is 001

Input A: 10 COMPARED with Input B: 01 is 100



## Question - 2
Write Python code that does the following. 

- Create the following functions, that will return the appropriate response as mentioned below for a given input bit.
    - function: **n_bit_left_shifter()**, Input: **input_value**, **n**. **input_value** where input_value will be unsigned n bit binary value and **n** will be an integer value which is the number of bits we want to left shift the input_value. This function should return the appropraite value as applied by LEFT SHIFT operation on the respective input_value bits
        - Ex: input_value = 1110, n = 2 then input_value LEFT SHIFT by n bits would result in output_value = 1000
        - Ex: input_value = 1001, n = 3 then input_value LEFT SHIFT by n bits would result in output_value = 0100
    - function: **n_bit_right_shifter()**, Input: **input_value**, **input_value** where input_value will be unsigned n bit binary value and n will be the number of bits we want to right shift the input_value. This function should return the appropraite value as applied by RIGHT SHIFT operation on the respective input_value bits
        - Ex: input_value = 1110, n = 2 then input_value RIGHT SHIFT by n bits would result in output_value = 0011
        - Ex: input_value = 1001, n = 3 then input_value RIGHT SHIFT by n bits would result in output_value = 0001

**Conditions to follow:**
- The output should be a string format similar to test cases mentioned below
- Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- No other function name can be defined/declared than the ones asked to be declared in any of the questions presented in this notebook. 
- The code you write should pass all the test cases given. 


---

TEST CASES:

```
Input: 1010 when LEFT SHIFTED by N: 3 bits is 0000

Input: 1010 when RIGHT SHIFTED by N: 3 bits is 0001

Input: 101110 when LEFT SHIFTED by N: 4 bits is 100000

Input: 101110 when RIGHT SHIFTED by N: 4 bits is 000010

Input: 1111 when LEFT SHIFTED by N: 3 bits is 1000

Input: 1111 when RIGHT SHIFTED by N: 3 bits is 0001
```
---

Hint: You can use built in methods and data type/string methods to create the solution, Consider list slicing to achieve the solution.

### Code

In [ ]:
# DECLARE the function n_bit_left_shifter()
def n_bit_left_shifter(input_value, n):
    # write code here

# DECLARE the function n_bit_right_shifter()
def n_bit_right_shifter(input_value, n):
    # write code here

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('10101', 2), ('10100', 1), ('01011', 4), ('111011', 5)]
for input_value, n in input_value_tuple_list:
    # CALL the n_bit_left_shifter with required parameters
    left_shift_output_value = n_bit_left_shifter(input_value=input_value, n=n)
    # CALL the n_bit_right_shifter with required parameters
    right_shift_output_value = n_bit_right_shifter(input_value=input_value, n=n)
    # Print the output
    print("Input: {0} when LEFT SHIFTED by N: {1} bits is {2}\n".format(input_value, n, left_shift_output_value))
    print("Input: {0} when RIGHT SHIFTED by N: {1} bits is {2}\n".format(input_value, n, right_shift_output_value))

### Solution

In [4]:
# DECLARE the function n_bit_left_shifter()
def n_bit_left_shifter(input_value, n):
    output_value = ""
    n = int(n)
    len_input_value = len(input_value)
    if n >= len_input_value:
        output_value = "0" * len_input_value
    else:
        output_value = input_value[n:] + "0" * n
    return output_value

# DECLARE the function n_bit_right_shifter()
def n_bit_right_shifter(input_value, n):
    output_value = ""
    n = int(n)
    len_input_value = len(input_value)
    if n >= len_input_value:
        output_value = "0" * len_input_value
    else:
        output_value = "0" * n + input_value[:(len_input_value - n)]
    return output_value

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('10101', 2), ('10100', 1), ('01011', 4), ('111011', 5)]
for input_value, n in input_value_tuple_list:
    # CALL the n_bit_left_shifter with required parameters
    left_shift_output_value = n_bit_left_shifter(input_value=input_value, n=n)
    # CALL the n_bit_right_shifter with required parameters
    right_shift_output_value = n_bit_right_shifter(input_value=input_value, n=n)
    # Print the output
    print("Input: {0} when LEFT SHIFTED by N: {1} bits is {2}\n".format(input_value, n, left_shift_output_value))
    print("Input: {0} when RIGHT SHIFTED by N: {1} bits is {2}\n".format(input_value, n, right_shift_output_value))

Input: 10101 when LEFT SHIFTED by N: 2 bits is 10100

Input: 10101 when RIGHT SHIFTED by N: 2 bits is 00101

Input: 10100 when LEFT SHIFTED by N: 1 bits is 01000

Input: 10100 when RIGHT SHIFTED by N: 1 bits is 01010

Input: 01011 when LEFT SHIFTED by N: 4 bits is 10000

Input: 01011 when RIGHT SHIFTED by N: 4 bits is 00000

Input: 111011 when LEFT SHIFTED by N: 5 bits is 100000

Input: 111011 when RIGHT SHIFTED by N: 5 bits is 000001



## Question - 3
Write Python code that does the following. 

- Create a function: **logical_alu()**, Input: **opcode**, **input_value_a**, **input_value_b**, **n** where input_value_a and input_value_b should be unsigned n bit binary value based on the opcode which is a strictly a 3 bit binary value and n is an integer. This function should perform the operations for the respective opcodes.
    - When opcode is of value 1 (001) then we perform AND GATE operation on the input_a and input_b values
    - When opcode is of value 2 (010) then we perform OR GATE operation on the input_a and input_b values
    - When opcode is of value 3 (011) then we perform XOR GATE operation on the input_a and input_b values
    - When opcode is of value 4 (100) then we perform FOUR BIT UNSIGNED ADDITION operation on the input_a and input_b values
    - When opcode is of value 5 (101) then we perform TWO BIT COMPARISON  operation on the input_a and input_b values
    - When opcode is of value 6 (110) then we perform N BIT LEFT SHIFT operation on the input_a values by n bits
    - When opcode is of value 6 (110) then we perform N BIT RIGHT SHIFT operation on the input_a values by n bits

**Conditions to follow:**
- The output should be a string format similar to test cases mentioned below
- Inbuilt functions which require no import and Datatype methods can be used to solve this problem but No arbitray functions or library can be used.
- No other function name can be defined/declared than the ones asked to be declared in any of the questions presented in this notebook. 
- The code you write should pass all the test cases given. 


---

TEST CASES:

```
Input A: 1101, Input B: 1001 for opcode: 001 is 1001

Input A: 101, Input B: 0011 for opcode: 010 is 0111

Input A: 0101, Input B: 1101 for opcode: 011 is 1000

Input A: 001, Input B: 1101 for opcode: 100 is 1110

Input A: 10, Input B: 01 for opcode: 101 is 100

Input A: 11101 with n: 3 for opcode: 110 is 01000

Input A: 11101010 with n: 4 for opcode: 111 is 00001110
```
---

Hint: You can use built in methods and data type/string methods to create the solution to solve this problem. Consider using the logic you have coded so far and converting the opcode to base 10 for easier handling.

### Code

In [ ]:
# DECLARE the function logical_alu()
def logical_alu(opcode, input_value_a="0000", input_value_b="0000", n=0):
    # write code here

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('1101', '1001', None, '001'),('101', '0011', None, '010'),('0101', '1101', None, '011'),('001', '1101', None, '100'),('10', '01', None, '101'),('11101', '', 3, '110'),('11101010', '', 4, '111')]
for input_value_a, input_value_b, n, opcode in input_value_tuple_list:
    # CALL the logical_alu with required parameters
    output_value = logical_alu(opcode=opcode, input_value_a=input_value_a, input_value_b=input_value_b, n=n)
    # Print the output
    if input_value_b:
        print("Input A: {0}, Input B: {1} for opcode: {2} is {3}\n".format(input_value_a, input_value_b, opcode, output_value))
    elif n:
        print("Input A: {0} with n: {1} for opcode: {2} is {3}\n".format(input_value_a, n, opcode, output_value))

### Solution

In [7]:
# DECLARE the function four_bit_unsigned_adder()
def four_bit_unsigned_adder(input_value_a, input_value_b):
    # We will use a 4-bit parallel adder logic
    input_value_a = input_value_a.zfill(4)
    input_value_b = input_value_b.zfill(4)
    # Initialize the output_value_list
    output_value_list = []
    # Initialize the carry from each addition which is initally 0
    carry = '0'
    # Iterate over each bit and add them, We need to start operating from LSB to MSB
    for bit_a, bit_b in zip(input_value_a[::-1], input_value_b[::-1]):
        # SUM = A XOR B XOR Ci
        sum = xor_gate(xor_gate(bit_a, bit_b)[-1], carry)[-1]
        # Insert Sum at MSB
        output_value_list.insert(0, sum)
        # CARRY = A.B + B.C + C.A
        a_and_b, b_and_c, c_and_a = and_gate(bit_a, bit_b)[-1], and_gate(bit_b, carry)[-1], and_gate(carry, bit_a)[-1]
        carry = or_gate(or_gate(a_and_b, b_and_c)[-1], c_and_a)[-1]
    # Add the carry bit to the MSB
    output_value_list.insert(0, carry)
    # Return the output value as string
    return "".join(output_value_list).lstrip('0')

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('1000', '01'), ('1010', '0101'), ('1110', '0111'), ('010', '111')]
for input_value_a, input_value_b in input_value_tuple_list:
    # CALL the four_bit_unsigned_adder with required parameters
    output_value = four_bit_unsigned_adder(input_value_a=input_value_a, input_value_b=input_value_b)
    # Print the output
    print("Input A: {0} ADDED Input B: {1} is {2}\n".format(input_value_a, input_value_b, output_value))

Input A: 1000 ADDED Input B: 01 is 1001

Input A: 1010 ADDED Input B: 0101 is 1111

Input A: 1110 ADDED Input B: 0111 is 10101

Input A: 010 ADDED Input B: 111 is 1001



In [8]:
# DECLARE the function four_bit_unsigned_subtractor()
def four_bit_unsigned_subtractor(input_value_a, input_value_b):
    # We will use a 4-bit parallel adder logic
    input_value_a = input_value_a.zfill(4)
    input_value_b = input_value_b.zfill(4)
    # We will create 1's compliment of the input_value_b using by using XOR gate on each bit with 1
    input_value_b = "".join([xor_gate(bit_b, '1')[-1] for bit_b in input_value_b])
    # Initialize the output_value_list
    output_value_list = []
    # Initialize the carry from each addition which is initally 1 which should make the input_value_b into 2's compliment
    carry = '1'
    # Iterate over each bit and add them, We need to start operating from LSB to MSB
    for bit_a, bit_b in zip(input_value_a[::-1], input_value_b[::-1]):
        # SUM = A XOR B XOR Ci
        sum = xor_gate(xor_gate(bit_a, bit_b)[-1], carry)[-1]
        # Insert Sum at MSB
        output_value_list.insert(0, sum)
        # CARRY = A.B + B.C + C.A
        a_and_b, b_and_c, c_and_a = and_gate(bit_a, bit_b)[-1], and_gate(bit_b, carry)[-1], and_gate(carry, bit_a)[-1]
        carry = or_gate(or_gate(a_and_b, b_and_c)[-1], c_and_a)[-1]
    if carry == '0':
        output_value_list = [xor_gate(output_bit, '1')[-1] for output_bit in output_value_list]
        output_value_list = list(four_bit_unsigned_adder(input_value_a="".join(output_value_list), input_value_b='1')[-4:])
        output_value_list.insert(0, '-')
    else:
        output_value_list.insert(0, '+')
    # Return the output value as string
    return "".join(output_value_list)

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('111', '010'), ('1010', '0101'), ('1110', '0111'), ('010', '111')]
for input_value_a, input_value_b in input_value_tuple_list:
    # CALL the four_bit_unsigned_subtractor with required parameters
    output_value = four_bit_unsigned_subtractor(input_value_a=input_value_a, input_value_b=input_value_b)
    # Print the output
    print("Input A: {0} SUBTRACTED Input B: {1} is {2}\n".format(input_value_a, input_value_b, output_value))

Input A: 111 SUBTRACTED Input B: 010 is +0101

Input A: 1010 SUBTRACTED Input B: 0101 is +0101

Input A: 1110 SUBTRACTED Input B: 0111 is +0111

Input A: 010 SUBTRACTED Input B: 111 is -101



In [9]:
# DECLARE the function logical_alu()
def logical_alu(opcode, input_value_a="0000", input_value_b="0000", n=0):
    output_value = ""
    opcode_in_base_10 = int(opcode, 2)
    if opcode_in_base_10 == 1:
        output_value = and_gate(input_value_a, input_value_b)
    elif opcode_in_base_10 == 2:
        output_value = or_gate(input_value_a, input_value_b)
    elif opcode_in_base_10 == 3:
        output_value = xor_gate(input_value_a, input_value_b)
    elif opcode_in_base_10 == 4:
        output_value = four_bit_unsigned_adder(input_value_a, input_value_b)
    elif opcode_in_base_10 == 5:
        output_value = two_bit_comparator(input_value_a[:2], input_value_b[:2])
    elif opcode_in_base_10 == 6:
        output_value = n_bit_left_shifter(input_value_a, n)
    elif opcode_in_base_10 == 7:
        output_value = n_bit_right_shifter(input_value_a, n)
    return output_value

### TEST CASES ###

# Initialize the input values
input_value_tuple_list = [('1101', '1001', None, '001'),('101', '0011', None, '010'),('0101', '1101', None, '011'),('001', '1101', None, '100'),('10', '01', None, '101'),('11101', '', 3, '110'),('11101010', '', 4, '111')]
for input_value_a, input_value_b, n, opcode in input_value_tuple_list:
    # CALL the logical_alu with required parameters
    output_value = logical_alu(opcode=opcode, input_value_a=input_value_a, input_value_b=input_value_b, n=n)
    # Print the output
    if input_value_b:
        print("Input A: {0}, Input B: {1} for opcode: {2} is {3}\n".format(input_value_a, input_value_b, opcode, output_value))
    elif n:
        print("Input A: {0} with n: {1} for opcode: {2} is {3}\n".format(input_value_a, n, opcode, output_value))

Input A: 1101, Input B: 1001 for opcode: 001 is 1001

Input A: 101, Input B: 0011 for opcode: 010 is 0111

Input A: 0101, Input B: 1101 for opcode: 011 is 1000

Input A: 001, Input B: 1101 for opcode: 100 is 1110

Input A: 10, Input B: 01 for opcode: 101 is 100

Input A: 11101 with n: 3 for opcode: 110 is 01000

Input A: 11101010 with n: 4 for opcode: 111 is 00001110

